### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Caiyulu-818** [EMBL-PKU/BASALT#1]
hello  I have two questions
first the parameter--long-reads which have two fa 1&2 ，but the long reads from nanopore is only One end , so just put the one fa ?
second error , There are the following error messages，
File "/public/home/XXX/miniconda3/envs/BASALT/bin/BASALT", line 56, in <module>
    datasets[str(n)].append(pr[1].strip())
IndexError: list index out of range
how can I solve this problem by changing some parameter？

**Comment by EMBL-PKU** [comment]
Thank you for using BASALT. Now BASALT has been updated. You can try again.

**Comment by raw937** [comment]
I had the same error. It's still not fixed. 
Traceback (most recent call last):
  File "/users/raw937/.conda/envs/BASALT/bin/BASALT", line 57, in <module>
    datasets[str(n)].append(pr[1].strip())
IndexError: list index out of range

In basalt main .py 
Line 57        f.write('BASALT started from 1st step'+'\n')

In BASALT
Line 54 datasets, n = {}, 0
for item in datasets_list:
    n+=1
Line 57    datasets[str(n)]=[]
    pr=str(item).split(',')
    datasets[str(n)].append(pr[0].strip())
    datasets[str(n)].append(pr[1].strip())
