### ISSUE TITLE
the threads setting is not applied for all implemented tools

### ISSUE THREAD

**Issue by liupfskygre** [EMBL-PKU/BASALT#17]
HI, 
    During the running of BASALT, I found the -t parameter is not used for tools, for example, 
semibin2, although I set -t 8, but it uses 40. 

Do we have way to solve this, otherwise it would occupied all my CPUs.

Thanks.

**Comment by EMBL-PKU** [comment]
Hi,
Thank you for raising this problem. We just fixed it!
Thank you again for supporting BASALT！ Please let us know if there is any other issue!
Best!
