### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by WUD2018** [EMBL-PKU/BASALT#18]
Hey developer,

Thanks for your contribution, I have installed the BASALT via conda. However, when I enter the environment, and type 'BASALT', the system reads; BASALT: command not found

Should I add it to the PATH? if so, by how, please let me know, thanks.

![snap](https://github.com/EMBL-PKU/BASALT/assets/42631911/2c3113e1-788c-46a4-83a0-c1b642ab1842)

Here is my installation process:

git clone https://github.com/EMBL-PKU/BASALT.git
cd ./BASALT
chmod -R 755 ./
mamba env create -n BASALT --file basalt_env.yml

**Comment by WUD2018** [comment]
![Uploading 捕获.JPG…]()

**Comment by Ma-Yingxue** [comment]
I just had the very same question, even with all three installation methods. Have you downloaded successfully?

**Comment by WUD2018** [comment]
Yes, all the packages have been successfully downloaded and installed (you may see my attached pics).

I tried conda and setup.py and none of them works.

**Comment by WUD2018** [comment]
Yes, I have tried -h and --help. Still the same problem. 'BASALT: command not found'

**Comment by zfsh** [comment]
I met the same trouble too, I wonder have you solved this problem? And how do you solve it, thanks.

**Comment by WUD2018** [comment]
not yet, still awaits the developer's feedback

**Comment by WUD2018** [comment]
not yet, still awaits the developer's feedback

**Comment by EMBL-PKU** [comment]
Hi, you need to put the BASALT_script.zip into your system. Please check whether this step has been done. If there is any question, please let me know.
Best,

**Comment by EMBL-PKU** [comment]
There is no BASALT command in the PATH for that environment (e.g. .conda/env/BASALT/bin). You may be able to solve this by manually unzipping BASALT/BASALT_script.zip and changing the permissions on BASALT/BASALT_script/BASALT.

**Comment by WUD2018** [comment]
> There is no BASALT command in the PATH for that environment (e.g. .conda/env/BASALT/bin). You may be able to solve this by manually unzipping BASALT/BASALT_script.zip and changing the permissions on BASALT/BASALT_script/BASALT.

Hello there,

I have done the same as you suggested, but it still did not work as we expected.

However, when I type the absolute path of BALST it seems to give some positive feedback.

![snapJPG](https://github.com/EMBL-PKU/BASALT/assets/42631911/2f77bdb9-4789-4660-b547-eeb4c93d1da8)

So, I still need to put the path of the script PATH in .bashrc

Thanks for your efforts and development of this software.

hope this comment can also help others.

**Comment by EMBL-PKU** [comment]
Thank you for your patient and support for BASALT. We are going to make this software better. Please let me know if there is any questions. We may also send an email to me in case sometimes I did not read the issue page.  My email is yuke.sz@pku.edu.cn

**Comment by WUD2018** [comment]
Dear developer,


Here is the issue, seems like the installation did not create a path in .cache? How can I solve it? Thanks. 


Processing assemblies: ['FC.lm.SwabRes.Sum.hrm.contigs.fa', 'FC.zl.SwabRes.Sum.hrm.contigs.fa', 'KC.hyq.SwabRes.Sum.hrm.contigs.fa', 'KC.xys.SwabRes.Sum.hrm.contigs.fa', 'LR.cz.SwabRes.Sum.hrm.contigs.fa', 'LR.hml.SwabRes.Sum.hrm.contigs.fa', 'LR.wbk.SwabRes.Sum.hrm.contigs.fa', 'LR.wmj.SwabRes.Sum.hrm.contigs.fa', 'LR.wny.SwabRes.Sum.hrm.contigs.fa', 'LR.wxn.SwabRes.Sum.hrm.contigs.fa', 'LR.zzf.SwabRes.Sum.hrm.contigs.fa', 'SB.hfl.SwabRes.Sum.hrm.contigs.fa', 'SB.lwh.SwabRes.Sum.hrm.contigs.fa', 'SB.slh.SwabRes.Sum.hrm.contigs.fa', 'TW.cy.SwabRes.Sum.hrm.contigs.fa', 'TW.cyz.SwabRes.Sum.hrm.contigs.fa', 'TW.djc.SwabRes.Sum.hrm.contigs.fa', 'TW.lcb.SwabRes.Sum.hrm.contigs.fa']
Processing short-reads: {'1': ['FC.lm.SwabRes.Sum.hrm_1.fq', 'FC.lm.SwabRes.Sum.hrm_2.fq'], '2': ['FC.zl.SwabRes.Sum.hrm_1.fq', 'FC.zl.SwabRes.Sum.hrm_2.fq'], '3': ['KC.hyq.SwabRes.Sum.hrm_1.fq', 'KC.hyq.SwabRes.Sum.hrm_2.fq'], '4': ['KC.xys.SwabRes.Sum.hrm_1.fq', 'KC.xys.SwabRes.Sum.hrm_2.fq'], '5': ['LR.cz.SwabRes.Sum.hrm_1.fq', 'LR.cz.SwabRes.Sum.hrm_2.fq'], '6': ['LR.hml.SwabRes.Sum.hrm_1.fq', 'LR.hml.SwabRes.Sum.hrm_2.fq'], '7': ['LR.wbk.SwabRes.Sum.hrm_1.fq', 'LR.wbk.SwabRes.Sum.hrm_2.fq'], '8': ['LR.wmj.SwabRes.Sum.hrm_1.fq', 'LR.wmj.SwabRes.Sum.hrm_2.fq'], '9': ['LR.wny.SwabRes.Sum.hrm_1.fq', 'LR.wny.SwabRes.Sum.hrm_2.fq'], '10': ['LR.wxn.SwabRes.Sum.hrm_1.fq', 'LR.wxn.SwabRes.Sum.hrm_2.fq'], '11': ['LR.zzf.SwabRes.Sum.hrm_1.fq', 'LR.zzf.SwabRes.Sum.hrm_2.fq'], '12': ['SB.hfl.SwabRes.Sum.hrm_1.fq', 'SB.hfl.SwabRes.Sum.hrm_2.fq'], '13': ['SB.lwh.SwabRes.Sum.hrm_1.fq', 'SB.lwh.SwabRes.Sum.hrm_2.fq'], '14': ['SB.slh.SwabRes.Sum.hrm_1.fq', 'SB.slh.SwabRes.Sum.hrm_2.fq'], '15': ['TW.cy.SwabRes.Sum.hrm_1.fq', 'TW.cy.SwabRes.Sum.hrm_2.fq'], '16': ['TW.cyz.SwabRes.Sum.hrm_1.fq', 'TW.cyz.SwabRes.Sum.hrm_2.fq'], '17': ['TW.djc.SwabRes.Sum.hrm_1.fq', 'TW.djc.SwabRes.Sum.hrm_2.fq'], '18': ['TW.lcb.SwabRes.Sum.hrm_1.fq', 'TW.lcb.SwabRes.Sum.hrm_2.fq']}
Processing long-reads: []
Processing hifi-reads: []
Processing Hi-C reads: []
Process with extra binner: []
Quality check software: checkm
Processing with: 90 threads
Processing with: 550 G
Running status: continue
Binning module: all
Min completeness: 50
Max contamination: 10
Autobinning parameter: more-sensitive
Refinement parameter: deep
Traceback (most recent call last):
  File "/home/dell/ToolsBin/BASALT/BASALT_script/BASALT", line 141, in
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/dell/ToolsBin/BASALT/BASALT_script/BASALT_main_c.py", line 30, in BASALT_main_c
    os.chdir(local_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/.cache/BASALT'



---------------------------------------


武冬 D. WU, PhD
华东师范大学生态与环境学学学院
Research Fellow
Zijiang Young Scholar
School of Ecological and Environmental Science
East China Normal University
Shanghai, China

https://www.researchgate.net/profile/Dong_Wu25
https://faculty.ecnu.edu.cn/_s31/wd2_en_19490/main.psp




On 4/5/2024 ***@***.***> wrote：


Thank you for your patient and support for BASALT. We are going to make this software better. Please let me know if there is any questions. We may also send an email to me in case sometimes I did not read the issue page. My email is ***@***.***

**Comment by B1991ing** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/.cache/BASALT'

Hi,

How do you finally solve the issue -  FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/.cache/BASALT'?

Best,

Bing
