### ISSUE TITLE
The issue of CheckM

### ISSUE THREAD

**Issue by Yanh35** [EMBL-PKU/BASALT#2]
When I tried to run this code, I got the following problem:
'''
 File "BASALT/BASALT_main.py", line 361, in BASALT_main
    contig_outlier_remover_main('BestBinset', coverage_matrix_list, connections_list, num_threads, ram)
  File "BASALT/S5_Outlier_remover_mpt_05162022.py", line 1335, in contig_outlier_remover_main
    bin_comparison(best_binset_from_multi_assemblies+'_coverage_refined', best_binset_from_multi_assemblies+'_TNFs_refined', 'fa', 'TNFs', num_threads, ram, pwd)
  File "BASALT/S5_Outlier_remover_mpt_05162022.py", line 722, in bin_comparison
    os.chdir(refined_binset+'_checkm/storage/')
FileNotFoundError: [Errno 2] No such file or directory: 'BestBinset_TNFs_refined_checkm/storage/'
'''
I also checked the file "BestBinset_TNFs_refined_checkm/checkm.log", it showed that 
'''
INFO: CheckM v1.1.3
INFO: checkm lineage_wf -t 40 -x fa BestBinset_TNFs_refined BestBinset_TNFs_refined_checkm
INFO: [CheckM - tree] Placing bins in reference genome tree.
ERROR: No bins found. Check the extension (-x) used to identify bins.
'''

**Comment by EMBL-PKU** [comment]
Thanks for using BASALT. We have fixed this error. You can try running again.
