### ISSUE TITLE
Only use contig

### ISSUE THREAD

**Issue by wangyujie000** [EMBL-PKU/BASALT#20]
I only wanted to use contigs to run, and the command was “BASALT -a 1.fasta -t 20 -m 120”
Here is error:
Traceback (most recent call last):
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/bin/BASALT", line 141, in <module>
    BASALT_main_c(assembly_list, datasets, num_threads, lr_list, hifi_list, hic_list, eb_list, ram, continue_mode, functional_module, autobining_parameters, refinement_paramter, max_ctn, min_cpn, pwd, QC_software)
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/bin/BASALT_main_c.py", line 258, in BASALT_main_c
    A=autobinner_main(assembly_list, datasets, lr_list, hifi_list, insert_size, num_threads, ram, autobining_parameters, QC_software, pwd)
  File "/home/xxx/mambaforge-pypy3/envs/BASALT/bin/S1_Autobinners_2qc_11152023.py", line 1109, in autobinner_main
    bam_sorted=bam_sorted2
UnboundLocalError: local variable 'bam_sorted2' referenced before assignment
Is there a solution? Or it has to be with SR dataset? Thank you!

**Comment by noddevil4949** [comment]
Hi,

Raw fasta files are essential to calculate the depth of contigs, therefore binning cannot proceed without raw reads. Please have another go once you have raw reads ready. Thanks for using BASALT!

Cheers
