### ISSUE TITLE
BASALT create some file named core.123xxx after running.

### ISSUE THREAD

**Issue by Songq-20** [EMBL-PKU/BASALT#22]
Hello, 
BASALT is an excellent tool.,I try it with test file, but BASALT creat some files named like `core.565273`. When I checked the log file, I did not find any exceptions.
How can I avoid generating these files? 
Thanks!

**Comment by EMBL-PKU** [comment]
Hi,
Thank you for using BASALT. We found no file like this 'core.56273' generated before. Could you please send me one of these files? I may need to check it. Thank you.

**Comment by Songq-20** [comment]
Sorry, I just checked and found that the core file is generated when the Linux process crashes and should be related to the allocation of core, memory or threads... 
We will conduct further debugging later. 
Thank you!
