### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by raw937** [EMBL-PKU/BASALT#3]
I had the same error. It's still not fixed.
Traceback (most recent call last):
File "/users/raw937/.conda/envs/BASALT/bin/BASALT", line 57, in
datasets[str(n)].append(pr[1].strip())
IndexError: list index out of range

In basalt main .py
Line 57 f.write('BASALT started from 1st step'+'\n')

In BASALT
Line 54 datasets, n = {}, 0
for item in datasets_list:
n+=1
Line 57 datasets[str(n)]=[]
pr=str(item).split(',')
datasets[str(n)].append(pr[0].strip())
datasets[str(n)].append(pr[1].strip())

**Comment by EMBL-PKU** [comment]
Hi,
Thank you for raising the issue. Sorry for the inconvenient. 
I think there is question of inputting the files. BASALT dose not support inputting the sequence files or assembly file with a path. For example, you could use this command to run BASALT:
1) BASALT -a a1.fa,a2.fa -s seq1_r1.fq,seq1_r2.fq/seq2_r1.fq,seq2_r2.fq -l ont_seq.fq -t 60 -m 250
But could not use the following command:
2) BASALT -a your_path/a1.fa,your_path/a2.fa -s your_path/seq1_r1.fq,your_path/seq1_r2.fq/your_path/seq2_r1.fq,your_path/seq2_r2.fq -l ont_seq.fq -t 60 -m 250
You may use current version of BASALT in the 1) way. And we will alter the script and support adding the path in the command in following one or two days. 
Thank you again for helping us to improving the software.
