### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by cc9678** [EMBL-PKU/BASALT#4]
Hi,

I had en error message when I ran "BASALT -a assembly.fasta -l barcode89_filtlong.fastq --module autobinning"

Traceback (most recent call last):
  File "/dss/dsshome1/lxc04/ge24yaf2/.conda/envs/BASALT/bin/BASALT", line 53, in <module>
    datasets_list=sr_datasets.split('/')

My sequences are nanopore long reads, therefore I don't have any input for -s option. This error seems points to the short pair-end reads, do you know how should I deal with it?

**Comment by noddevil4949** [comment]
Hi,

Thank you for using BASALT. Unfortunately, BASALT does not support long-read sequences alone for binning at the moment, because it does not generate proper contig coverage from nanopore reads. You may have a try with short+long reads if there is any dataset available.

Regards,
Galaxy
