### ISSUE TITLE
VAMB and BASALT

### ISSUE THREAD

**Issue by vicru93** [EMBL-PKU/BASALT#41]
Hi:

I have this command line to use BASALT: 

BASALT -a A18_Assembly.fa -s A18_1.fq.gz,A18_2.fq.gz -t 20 -m 130 -q checkm -e A18_bins_Vamb/

Additionally, I have this directory with "bins" that I got from VAMB, my question is if the command line that I am using for BASALT is correct or if I should add these "bins" in another way?

My VAMB bins directory looks like this:
cd A18_bins_Vamb/
(base) [v.rua@hypatia A18_bins_Vamb]$ ls
S1C10921.fa  S1C13208.fa  S1C14509.fa  S1C1511.fa   S1C16750.fa  S1C20640.fa  S1C2204.fa   S1C23356.fa  S1C2489.fa  S1C42.fa    S1C5541.fa  S1C8183.fa
S1C11165.fa  S1C13752.fa  S1C14573.fa  S1C15510.fa  S1C18877.fa  S1C21133.fa  S1C2224.fa   S1C23436.fa  S1C2680.fa  S1C5064.fa  S1C5844.fa  S1C852.fa
S1C1290.fa   S1C13897.fa  S1C14655.fa  S1C16116.fa  S1C19787.fa  S1C21229.fa  S1C22281.fa  S1C2354.fa   S1C2959.fa  S1C5172.fa  S1C6138.fa  S1C901.fa
S1C13001.fa  S1C13960.fa  S1C14690.fa  S1C164.fa    S1C20086.fa  S1C2134.fa   S1C22480.fa  S1C2396.fa   S1C3200.fa  S1C5323.fa  S1C670.fa   S1C9403.fa
S1C13123.fa  S1C1404.fa   S1C14991.fa  S1C16714.fa  S1C20529.fa  S1C2197.fa   S1C2310.fa   S1C24119.fa  S1C334.fa   S1C5471.fa  S1C6970.fa  S1C9685.fa

**Comment by noddevil4949** [comment]
Hi,

When using existing bins obtained earlier, you can use -d function to add extra bins. Using your command, it would be like this:
BASALT -a A18_Assembly.fa -s A18_1.fq.gz,A18_2.fq.gz -t 20 -m 130 -q checkm -d A18_bins_Vamb

Please make sure that BASALT version has been updated to v1.1.0 as this function is disabled in previous versions.

Cheers,
BASALT team

**Comment by vicru93** [comment]
ok, thanks :)

**Comment by vicru93** [comment]
ok, thanks :)
