### ISSUE TITLE
 "1_DRRcontigs.fasta" does not exist or is not a Bowtie 2 index

### ISSUE THREAD

**Issue by Juzishh** [EMBL-PKU/BASALT#51]
Dear BASALT Team:
Thanks for such an amazing tool.
However I am running the 'Building Bowtie2 index' of BASALT with two problems.

Command: BASALT -a DRRcontigs.fasta -s filtered1.fastq,filtered2.fastq -t 32 -m 384 --min-cpn 50 --max-ctn 10

First, During Building Bowtie2 index:
Settings:
  Output files: "1_DRRcontigs.fasta.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  1_DRRcontigs.fasta
Warning: Empty fasta file: '1_DRRcontigs.fasta'
Warning: All fasta inputs were empty
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: /work/home/acsxe0ht0t/miniconda3/envs/NEWBASALT/bin/bowtie2-build-s --wrapper basic-0 1_DRRcontigs.fasta 1_DRRcontigs.fasta 
Done!

Second, During Mapping datasets to contigs/scaffolds:
(ERR): "1_DRRcontigs.fasta" does not exist or is not a Bowtie 2 index
Exiting now ...
[E::hts_open_format] Failed to open file 1_DNA-1.sam
samtools view: failed to open "1_DNA-1.sam" for reading: No such file or directory
Cannot open the infile 1_DNA-1.sam
mv: cannot stat ‘condensed.cytoscape.connections.tab’: No such file or directory
rm: cannot remove ‘1_DNA-1.sam’: No such file or directory

Any response would be greatly appreciated!

**Comment by noddevil4949** [comment]
Hi,

Thanks for your question. It looks like 1_DRRcontigs.fasta did not generate properly. Maybe have a check of the input fasta file "DRRcontigs.fasta" to see if it is intact and not compressed? Please provide a bit more details of the fasta file (e.g., the size of the file, head lines, etc.) if this error persists.

Cheers,
BASALT team

**Comment by Juzishh** [comment]
Thanks for the reply!
The problem is solved after regenerating the fasta file.
